version: "3.8"

services:
  # Figure Backend Office (Admin UI)
  figure-backend-office:
    build:
      context: ./figure-backend-office
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - HOSTNAME=0.0.0.0
      - BACKEND_API_URL=http://figure-backend:8001
      - NEXT_PUBLIC_API_URL=http://localhost:8001
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./figure-backend-office:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      figure-backend:
        condition: service_healthy
    networks:
      - figure-network
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3001', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => { process.exit(1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Figure MCP Server (Production Only - 개발시에는 figure-mcp-proxy 사용)
  figure-mcp-server:
    build:
      context: ./figure-mcp-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BACKEND_API_URL=http://figure-backend:8001/api
    # volumes: # 운영환경에서는 볼륨 마운트 제거
    #   - ./figure-mcp-server:/app
    #   - /app/node_modules
    depends_on:
      figure-backend:
        condition: service_healthy
    networks:
      - figure-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - production  # 프로파일 추가로 선택적 실행

  # Figure Backend API
  figure-backend:
    build:
      context: ./figure-backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      # App Configuration
      - FIGURE_APP_NAME=Figure Backend
      - FIGURE_DEBUG=false
      - FIGURE_API_VERSION=v1

      # Server Configuration
      - FIGURE_HOST=0.0.0.0
      - FIGURE_PORT=8001

      # Provider 설정 (헥사고날 아키텍처) - .env 파일에서 참조
      - FIGURE_LLM_PROVIDER=claude
      - FIGURE_EMBEDDING_PROVIDER=voyage

      # Anthropic Claude API Configuration (기본 LLM 프로바이더)
      - FIGURE_CLAUDE_API_KEY=sk-test-dummy-key-for-development
      - FIGURE_CLAUDE_MODEL=claude-3-5-sonnet-20241022
      - FIGURE_CLAUDE_MAX_TOKENS=4096
      - FIGURE_CLAUDE_TEMPERATURE=0.1

      # Google Gemini API Configuration (임베딩 프로바이더)
      - FIGURE_GEMINI_API_KEY=dummy-gemini-key
      - FIGURE_GEMINI_MODEL=gemini-1.5-flash
      - FIGURE_GEMINI_EMBEDDING_MODEL=models/text-embedding-004
      - FIGURE_GEMINI_MAX_TOKENS=2048
      - FIGURE_GEMINI_TEMPERATURE=0.1

      # Groq API Configuration (Optional)
      - FIGURE_GROQ_API_KEY=dummy-groq-key
      - FIGURE_GROQ_MODEL=llama3-8b-8192

      # OpenAI API Configuration (임시 더미 키)
      - FIGURE_OPENAI_API_KEY=sk-test-dummy-openai-key-for-development-testing
      - FIGURE_OPENAI_MODEL=gpt-4o-mini
      - FIGURE_OPENAI_EMBEDDING_MODEL=text-embedding-3-large
      - FIGURE_OPENAI_MAX_TOKENS=4096
      - FIGURE_OPENAI_TEMPERATURE=0.1

      # Voyage AI API Configuration (기본 임베딩 프로바이더)
      - FIGURE_VOYAGE_API_KEY=pa-test-dummy-voyage-key-for-development
      - FIGURE_VOYAGE_EMBEDDING_MODEL=voyage-3-large

      # Storage Configuration
      - FIGURE_STORAGE_PROVIDER=local
      - FIGURE_LOCAL_STORAGE_PATH=/app/storage

      # Database Configuration
      - FIGURE_DATABASE_URL=sqlite:///./data/figure.db

      # SSL 인증서 문제 해결 (개발 환경용)
      - PYTHONHTTPSVERIFY=0

      # 임시 디렉토리 및 캐시 설정
      - TMPDIR=/tmp
      - HOME=/app
      - XDG_CACHE_HOME=/app/.cache
      - TRANSFORMERS_CACHE=/app/.cache/transformers
      - HF_HOME=/app/.cache/huggingface

      # ChromaDB Configuration
      - FIGURE_CHROMA_PERSIST_DIRECTORY=/app/data/chroma
      - FIGURE_CHROMA_COLLECTION_NAME=figure_documents

      # JIRA Configuration (선택사항)
      - FIGURE_JIRA_SERVER=${FIGURE_JIRA_SERVER:-}
      - FIGURE_JIRA_EMAIL=${FIGURE_JIRA_EMAIL:-}
      - FIGURE_JIRA_API_TOKEN=${FIGURE_JIRA_API_TOKEN:-}

    volumes:
      - ./figure-backend/data:/app/data
      - ./figure-backend/logs:/app/logs
      - ./backups:/app/backups  # 백업 디렉토리 추가
    depends_on:
      - chroma
    networks:
      - figure-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ChromaDB Vector Database
  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    environment:
      - CHROMA_HOST=0.0.0.0
      - CHROMA_PORT=8000
      - ALLOW_RESET=TRUE
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - figure-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v2/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis (선택사항 - 캐싱/세션 관리용)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - figure-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  chroma_data:
    driver: local
  redis_data:
    driver: local

networks:
  figure-network:
    driver: bridge
