from setuptools import setup, find_packages

setup(
    name="figure-mcp-document-processor",
    version="1.0.0",
    description="Figure-MCP 문서 처리 서비스",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.9",
    install_requires=[
        "fastapi>=0.104.0",
        "uvicorn>=0.24.0",
        "python-multipart>=0.0.6",
        "pydantic>=2.5.0",
        "pandas>=2.1.0",
        "openpyxl>=3.1.0",
        "python-docx>=1.1.0",
        "PyPDF2>=3.0.0",
        "pdfplumber>=0.10.0",
        "markdown>=3.5.0",
        "nltk>=3.8.0",
        "spacy>=3.7.0",
        "sentence-transformers>=2.2.0",
        "openai>=1.3.0",
        "chromadb>=0.4.0",
        "pinecone-client>=2.2.0",
        "weaviate-client>=3.25.0",
        "redis>=5.0.0",
        "psycopg2-binary>=2.9.0",
        "python-dotenv>=1.0.0",
        "requests>=2.31.0",
        "aiofiles>=23.2.0",
        "httpx>=0.25.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "pytest-asyncio>=0.21.0",
            "black>=23.0.0",
            "flake8>=6.0.0",
            "mypy>=1.0.0",
        ]
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ],
) 